export { registerRoute, getRoutes, clearRoutes } from './routeCollector';
export { buildOpenAPISpec } from './schemaBuilder';
export { invalidateCache, isCacheDirty, setCache, getCache, getLastUpdatedAt } from './specCache';
export { generateSpec, generateSpecJSON } from './specGenerator';
export { filterRoutes, groupRoutesByTag } from './routeFilter';
export { validateRoute, validateRoutes } from './routeValidator';
export { normalizeRoute, normalizeRoutes, normalizePath, normalizeTags } from './routeNormalizer';
export { toYAML, exportSpec, exportSpecToFile } from './routeExporter';
export { searchRoutes, extractSearchQuery } from './routeSearch';
export type { SearchOptions, SearchResult } from './routeSearch';
